/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UpstreamModelsRouteImport } from './routes/upstream-models'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestLogsRouteImport } from './routes/request-logs'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DownstreamModelsRouteImport } from './routes/downstream-models'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppKeysRouteImport } from './routes/app-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UpstreamModelsRoute = UpstreamModelsRouteImport.update({
  id: '/upstream-models',
  path: '/upstream-models',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLogsRoute = RequestLogsRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DownstreamModelsRoute = DownstreamModelsRouteImport.update({
  id: '/downstream-models',
  path: '/downstream-models',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/app-keys',
  path: '/app-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-keys': typeof AppKeysRoute
  '/dashboard': typeof DashboardRoute
  '/downstream-models': typeof DownstreamModelsRoute
  '/models': typeof ModelsRoute
  '/providers': typeof ProvidersRoute
  '/request-logs': typeof RequestLogsRoute
  '/settings': typeof SettingsRoute
  '/upstream-models': typeof UpstreamModelsRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-keys': typeof AppKeysRoute
  '/dashboard': typeof DashboardRoute
  '/downstream-models': typeof DownstreamModelsRoute
  '/models': typeof ModelsRoute
  '/providers': typeof ProvidersRoute
  '/request-logs': typeof RequestLogsRoute
  '/settings': typeof SettingsRoute
  '/upstream-models': typeof UpstreamModelsRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-keys': typeof AppKeysRoute
  '/dashboard': typeof DashboardRoute
  '/downstream-models': typeof DownstreamModelsRoute
  '/models': typeof ModelsRoute
  '/providers': typeof ProvidersRoute
  '/request-logs': typeof RequestLogsRoute
  '/settings': typeof SettingsRoute
  '/upstream-models': typeof UpstreamModelsRoute
  '/users': typeof UsersRoute
  '/auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-keys'
    | '/dashboard'
    | '/downstream-models'
    | '/models'
    | '/providers'
    | '/request-logs'
    | '/settings'
    | '/upstream-models'
    | '/users'
    | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-keys'
    | '/dashboard'
    | '/downstream-models'
    | '/models'
    | '/providers'
    | '/request-logs'
    | '/settings'
    | '/upstream-models'
    | '/users'
    | '/auth/login'
  id:
    | '__root__'
    | '/'
    | '/app-keys'
    | '/dashboard'
    | '/downstream-models'
    | '/models'
    | '/providers'
    | '/request-logs'
    | '/settings'
    | '/upstream-models'
    | '/users'
    | '/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppKeysRoute: typeof AppKeysRoute
  DashboardRoute: typeof DashboardRoute
  DownstreamModelsRoute: typeof DownstreamModelsRoute
  ModelsRoute: typeof ModelsRoute
  ProvidersRoute: typeof ProvidersRoute
  RequestLogsRoute: typeof RequestLogsRoute
  SettingsRoute: typeof SettingsRoute
  UpstreamModelsRoute: typeof UpstreamModelsRoute
  UsersRoute: typeof UsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upstream-models': {
      id: '/upstream-models'
      path: '/upstream-models'
      fullPath: '/upstream-models'
      preLoaderRoute: typeof UpstreamModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-logs': {
      id: '/request-logs'
      path: '/request-logs'
      fullPath: '/request-logs'
      preLoaderRoute: typeof RequestLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downstream-models': {
      id: '/downstream-models'
      path: '/downstream-models'
      fullPath: '/downstream-models'
      preLoaderRoute: typeof DownstreamModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-keys': {
      id: '/app-keys'
      path: '/app-keys'
      fullPath: '/app-keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppKeysRoute: AppKeysRoute,
  DashboardRoute: DashboardRoute,
  DownstreamModelsRoute: DownstreamModelsRoute,
  ModelsRoute: ModelsRoute,
  ProvidersRoute: ProvidersRoute,
  RequestLogsRoute: RequestLogsRoute,
  SettingsRoute: SettingsRoute,
  UpstreamModelsRoute: UpstreamModelsRoute,
  UsersRoute: UsersRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
